#!/bin/bash
### BEGIN INIT INFO
# Provides:          S9011sNatsMesh
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start S9011sNatsMesh during boot time
# Description:       wifi mesh daemon for configuring mesh network
#                    automatically
### END INIT INFO

source /opt/mesh-helper.sh
# sources mesh configuration
source_configuration

RADIO_INDEX=$2
DAEMON="mesh-11s_nats.sh"
DIR="/opt/"
_WIFI="${RADIO_INDEX}_MESH_VIF"
_MODE="${RADIO_INDEX}_MODE"
PIDFILE="/var/run/${DAEMON}_${RADIO_INDEX}_${!_WIFI}.pid"
LOG_FILE=/opt/mesh_11s_${RADIO_INDEX}_${!_WIFI}.log

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

start() {
    printf 'Starting %s: ' "$DAEMON"
    if [ "${!_MODE}" == "mesh" ] || [ "${!_MODE}" == "halow" ]; then
      start-stop-daemon -b -m -S -q -p "$PIDFILE" -a /bin/bash -- -c "exec $DIR$DAEMON ${!_MODE} $RADIO_INDEX > $LOG_FILE 2>&1"
      status=$?
      if [ "$status" -eq 0 ]; then
          echo "OK"
      else
          echo "FAIL"
      fi
    else
      echo "mesh/halow not starting..."
      return 0
    fi
    return "$status"
}
stop() {
    printf 'Stopping %s: ' "$DAEMON"
    NEW_PID=$(ps ax | grep -E 'wpa_supplicant\-11s' | awk {'print $1'})
    kill -9 $NEW_PID
    rm -fr /var/run/wpa_supplicant/* 2>/dev/null
    ifconfig "$MESH_VIF" down 2>/dev/null
    start-stop-daemon -K -o -q -p "$PIDFILE"
    status=$?
    if [ "$status" -eq 0 ]; then
        rm -f "$PIDFILE"
        echo "OK"
    else
        echo "FAIL"
    fi
    return "$status"
}
restart() {
    stop
    sleep 1
    start
}
case "$1" in
    start|stop|restart)
        "$1";;
    reload)
        # Restart, since there is no true "reload" feature.
        restart;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit 0
