#!/bin/bash

source /opt/mesh-helper.sh
# sources mesh configuration

RADIO_INDEX=$2   # $1: index of the mesh.conf file to be used e.g. "id0"

source_configuration "${RADIO_INDEX:2}"

DAEMON="mesh-11s_nats.sh"
DIR="/opt/"
_WIFI="${RADIO_INDEX}_MESH_VIF"
_MODE="${RADIO_INDEX}_MODE"
LOG_FILE=/opt/mesh-11s_AP_${RADIO_INDEX}.log

# The daemon's name (to ensure uniqueness and for stop, restart and status)
name="mesh-11s_nats_AP_${RADIO_INDEX}"

# The path of the daemon executable
daemon="/usr/bin/daemon"

# Other configuration parameters for the service
pidfiles="/var/run"
user=""
chroot=""
chdir=""
umask=""
stdout="$LOG_FILE"
stderr="$LOG_FILE"
daemon_start_args="--delay=11 --attempts=1 --respawn --ignore-eof"

case "$1" in
    start)
      if [ "${!_MODE}" == "ap+mesh_mcc" ] || [ "${!_MODE}" == "ap+mesh_scc" ]; then

        if "$daemon" --running --name "$name" --pidfiles "$pidfiles"
        then
            echo "$name is already running."
        else
            echo "Starting $name..."
            "$daemon" $daemon_start_args \
                --name "$name" --pidfiles "$pidfiles" \
                ${user:+--user $user} ${chroot:+--chroot $chroot} \
                ${chdir:+--chdir $chdir} ${umask:+--umask $umask} \
                ${stdout:+--stdout $stdout} ${stderr:+--stderr $stderr} \
                -- $DIR$DAEMON ${!_MODE} $RADIO_INDEX
            echo done.
        fi
       else
          echo "ap+mesh not starting..."
          echo "S90APoint: ap+mesh not starting..."
          exit 0
       fi
        ;;

    stop)
        if "$daemon" --running --name "$name" --pidfiles "$pidfiles"
        then
            echo "Stopping $name..."
            "$daemon" --stop --name "$name" --pidfiles "$pidfiles"
            echo done.

            NEW_PID=$(ps ax | awk "/ostapd-$RADIO_INDEX/{print \$1; exit}")
            if [ -n "$NEW_PID" ]; then
                kill "$NEW_PID" 2>/dev/null
                sleep 1
                ! kill -0 "$NEW_PID" 2>/dev/null || kill -9 "$NEW_PID" 2>/dev/null
            fi
            ifconfig "${!_WIFI}"-1 down 2>/dev/null
            iw dev "${!_WIFI}"-1 del 2>/dev/null
            ifname_ap=$(ifconfig -a | awk -F':' '/!_WIFI/{print $1; exit}')
            ifconfig "$ifname_ap" down 2>/dev/null
            iw dev "$ifname_ap" del 2>/dev/null
            ps aux | awk "/radvd.+(${!_WIFI// /|})/&&!/awk/{system(\"kill \" \$1 \" || :\")}" 2>/dev/null
        else
            echo "$name is not running."
        fi
        ;;


    restart|reload)
        "$0" stop "$2"
        sleep 2
        "$0" start "$2"
        ;;

    status)
        "$daemon" --running --name "$name" --pidfiles "$pidfiles" --verbose
        ;;


    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit 0
