#!/bin/bash
### BEGIN INIT INFO
# Provides:          S90MS15
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start S90MS15 Mesh Shield 1.5
# Description:       start S90MS15 Mesh Shield 1.5 beside other services
#
### END INIT INFO

DAEMON="main.py"
DIR="/opt/"
PIDFILE="/var/run/{$DAEMON}_ms15.pid"
LOG_FILE=/opt/mesh_shield_1.5.log

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

start() {
	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -a /bin/bash -- -c "exec python $DIR$DAEMON \
          $ARGS > $LOG_FILE 2>&1"
	status=$?
	if [ "$status" -eq 0 ]; then
	  echo "OK"
	else
	  echo "FAIL"
	fi
    return "$status"
}
stop() {
    printf 'Stopping %s: ' "$DAEMON"
    start-stop-daemon -K -q -p "$PIDFILE"
    status=$?
    if [ "$status" -eq 0 ]; then
        rm -f "$PIDFILE"
        echo "OK"
    else
        echo "FAIL"
    fi
    return "$status"
}
restart() {
    stop
    sleep 1
    start
}
case "$1" in
    start|stop|restart)
        "$1";;
    reload)
        # Restart, since there is no true "reload" feature.
        restart;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit 0
