#!/bin/bash
### BEGIN INIT INFO
# Provides:          S90mdm_agent
# Short-Description: MDM client
# Description:       Starts comms controller as MDM client
### END INIT INFO

DAEMON="comms_nats_controller.py"
DIR="/opt/nats/"
PIDFILE="/var/run/$DAEMON.pid"
# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"
LOG_FILE=/opt/mdm_agent.log

# TODO testing purposes
BC_KEY_FILE="/opt/certs/CBMA/BirthCerts/csl1.local.key"
BC_CERT_FILE="/opt/certs/CBMA/BirthCerts/csl1.local.crt"
BC_CA_FILE="/opt/certs/CBMA/BirthCerts/ca.crt"

# TODO naming
CBMA_KEY_FILE="/opt/certs/CBMA/LowerCBMA/csl1.local.key"
CBMA_CERT_FILE="/opt/certs/CBMA/LowerCBMA/csl1.local.crt"
CBMA_CA_FILE="/opt/certs/CBMA/LowerCBMA/ca.crt"



if [ -e "$BC_CA_FILE" ] && [ -e "$BC_KEY_FILE" ] && [ -e "$BC_CERT_FILE" ]; then
  ARGS="-k $BC_KEY_FILE -c $BC_CERT_FILE -r $BC_CA_FILE --agent mdm"
elif [ -e "$CBMA_KEY_FILE" ] && [ -e "$CBMA_CERT_FILE" ] && [ -e "$CBMA_CA_FILE" ]; then
  ARGS="-k $CBMA_KEY_FILE -c $CBMA_CERT_FILE -r $CBMA_CA_FILE --agent mdm"
else
  ARGS="--agent mdm"
fi

start() {
    echo "$ARGS"
    printf 'Starting %s: ' "$DAEMON"
    start-stop-daemon -b -m -S -q -p "$PIDFILE" -a /bin/bash -- -c "exec python $DIR$DAEMON \
          $ARGS > $LOG_FILE 2>&1"
    status=$?
    if [ "$status" -eq 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
    return "$status"
}

stop() {
    printf 'Stopping %s: ' "$DAEMON"
    start-stop-daemon -K -q -p "$PIDFILE"
    status=$?
    if [ "$status" -eq 0 ]; then
        rm -f "$PIDFILE"
        echo "OK"
    else
        echo "FAIL"
    fi
    return "$status"
}
restart() {
    stop
    sleep 1
    start
}
case "$1" in
    start|stop|restart)
        "$1";;
    reload)
        # Restart, since there is no true "reload" feature.
        restart;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit 0

