#!/bin/bash
### BEGIN INIT INFO
# Provides:          S9011sMesh
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start S9011sMesh during boot time
# Description:       wifi mesh daemon for configuring mesh network
#                    automatically
### END INIT INFO

DAEMON="mesh-11s.sh"
DIR="/opt/"
PIDFILE="/var/run/$DAEMON.pid"
LOG_FILE=/opt/mesh_11s.log

source /opt/mesh-helper.sh
# sources mesh configuration
source_configuration

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

start() {
    printf 'Starting %s: ' "$DAEMON"
    start-stop-daemon -b -m -S -q -p "$PIDFILE" -a /bin/bash -- -c "exec $DIR$DAEMON mesh > $LOG_FILE 2>&1"
    status=$?
    if [ "$status" -eq 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
    return "$status"
}
stop() {
    printf 'Stopping %s: ' "$DAEMON"
    NEW_PID=$(ps ax | grep -E 'wpa_supplicant\-11s' | awk {'print $1'})
    kill -9 $NEW_PID
    rm -fr /var/run/wpa_supplicant/* 2>/dev/null
    ifconfig "$MESH_VIF" down 2>/dev/null
    start-stop-daemon -K -o -q -p "$PIDFILE"
    status=$?
    if [ "$status" -eq 0 ]; then
        rm -f "$PIDFILE"
        echo "OK"
    else
        echo "FAIL"
    fi
    return "$status"
}
restart() {
    stop
    sleep 1
    start
}
case "$1" in
    start|stop|restart)
        "$1";;
    reload)
        # Restart, since there is no true "reload" feature.
        restart;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit 0
