#!/bin/bash

cat <<EOF >/usr/lib/NetworkManager/conf.d/unamaged_wifi_interfaces.conf
#
# All wl* interfaces are unmanaged
#
# See man NetworkManager.conf
#

[keyfile]
unmanaged-devices=interface-name:wl*
EOF
