# fog-sw BUILDER
ARG FROM_IMAGE
FROM $FROM_IMAGE as fog-sw-builder
ARG ROS_DISTRO="galactic"
ARG PACKAGE_NAME

WORKDIR /$PACKAGE_NAME/main_ws

USER root

ADD . /$PACKAGE_NAME/main_ws/src

WORKDIR /$PACKAGE_NAME/main_ws/src

RUN modules/mesh_com/package.sh 0 focal \

RUN dpkg -i modules/*.deb

COPY modules/mesh_com/entrypoint-init.sh /$PACKAGE_NAME/entrypoint.sh

ENV PACKAGE_NAME $PACKAGE_NAME
WORKDIR /$PACKAGE_NAME
ENTRYPOINT "/"$PACKAGE_NAME"/entrypoint.sh"
