# fog-sw BUILDER
ARG FROM_IMAGE
FROM $FROM_IMAGE as fog-sw-builder
ARG ROS_DISTRO="galactic"
ARG UID=1000
ARG GID=1000
ARG PACKAGE_NAME

WORKDIR /$PACKAGE_NAME/main_ws
USER root
ADD . /$PACKAGE_NAME/main_ws/src
RUN chown -R builder:builder /$PACKAGE_NAME/main_ws

USER builder

#Build here

WORKDIR /$PACKAGE_NAME/main_ws/src

RUN modules/mesh_com/package.sh 0 focal

USER root

RUN dpkg -i modules/*.deb

COPY modules/mesh_com/entrypoint.sh /$PACKAGE_NAME/entrypoint.sh

USER builder

ENV PACKAGE_NAME $PACKAGE_NAME
WORKDIR /$PACKAGE_NAME
ENTRYPOINT "/"$PACKAGE_NAME"/entrypoint.sh"
